//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worckers
    {
        public int Id { get; set; }
        public int IdRole { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string UserPastname { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Pass { get; set; }
        public string Mpbile { get; set; }
        public string Pasport { get; set; }
        public string Date { get; set; }
        public Nullable<int> TypeEnter { get; set; }
        public string LastEnter { get; set; }
        public Nullable<int> idSex { get; set; }
    
        public virtual Enter Enter { get; set; }
        public virtual Role Role { get; set; }
        public virtual Sex Sex { get; set; }
    }
}
